		var mobilia_brandnumber = 6,
			mobilia_brandscrollnumber = 2,
			mobilia_brandpause = 3000,
			mobilia_brandanimate = 2000;
		var mobilia_brandscroll = false;
							mobilia_brandscroll = true;
					var mobilia_categoriesnumber = 6,
			mobilia_categoriesscrollnumber = 2,
			mobilia_categoriespause = 3000,
			mobilia_categoriesanimate = 700;
		var mobilia_categoriesscroll = false;
					var mobilia_blogpause = 3000,
			mobilia_bloganimate = 2000;
		var mobilia_blogscroll = false;
							mobilia_blogscroll = false;
					var mobilia_testipause = 3000,
			mobilia_testianimate = 2000;
		var mobilia_testiscroll = false;
							mobilia_testiscroll = false;
					var mobilia_catenumber = 6,
			mobilia_catescrollnumber = 2,
			mobilia_catepause = 3000,
			mobilia_cateanimate = 700;
		var mobilia_catescroll = false;
					var mobilia_menu_number = 9;
		var mobilia_sticky_header = false;
							mobilia_sticky_header = false;
					